#ifndef M2026ROBOCONLIB_SETTING_HPP_INCLUDE_GUARD
#define M2026ROBOCONLIB_SETTING_HPP_INCLUDE_GUARD

#include "2026roboconlib/lib.hpp"

/*									 PWM1,PWM2,OUT3
#define ROBOSEPARATEBOARD_MD1_PINSET PB_4,PC_8,PA_15
#define ROBOSEPARATEBOARD_MD2_PINSET PC_9,PB_8,PD_2
#define ROBOSEPARATEBOARD_MD3_PINSET PB_3,PA_10,PC_2
#define ROBOSEPARATEBOARD_MD4_PINSET PB_10,PB_5,PC_3
#define ROBOSEPARATEBOARD_MD5_PINSET PA_11,PB_2,PB_12
#define ROBOSEPARATEBOARD_MD6_PINSET PB_7,PC_1,PA_4
*/

namespace rob{
extern aRotaryEncoder rotaryEncoder1;
extern aRotaryEncoder rotaryEncoder2;

}
#endif